#!/usr/bin/env python3
"""hgc_scaffold.py <HgcClass> [framework=Helium] — emit a fill-in-the-blanks skeleton for an
Hgc* shader-node port.

The Hgc* family (HgcGradient*, HgcST2084_*, HgcBT2100_*, HgcApply*LUT*, Hgc color nodes...) all
share ONE 17-method skeleton: a HGNode subclass implementing the Hgc render protocol
  ctor(s) / dtor triple (D0/D1/D2) / GetProgram / InitProgramDescriptor / shaderDescription /
  BindTexture / Bind / RenderTile / RenderTile_AVX / GetDOD / GetROI / SetParameter /
  GetParameter / GetOutput
differing only in: param count, alloc size, the const-fill quads, the shaderDescription string,
the embedded Metal fragment source, and the installed vtable address. Rebuilding that structure
from scratch per class is the bulk of an Hgc worker's budget.

This scaffold does the mechanical 80%: resolves every method's @0xADDR from the symmap, pulls the
shaderDescription + Metal source strings out of the binary where derivable, computes the vtable
install pointer (vtable-sym + 0x10), and writes a COMPILABLE skeleton .ts where every protocol
method is an @0xADDR-cited throwing stub (so the anti-shortcut gate P4 is satisfied and tsgo passes)
plus TODO anchors for the const-fill. The worker then fills bodies + const quads (using
`resolve.py <FW> ripconst` for the RIP-relative constants) instead of re-deriving the skeleton.

Usage:
  hgc_scaffold.py HgcGradientRadialTranslate            # framework defaults to Helium
  hgc_scaffold.py HgcSomeNode ProChannel > /tmp/x.ts    # inspect before writing
It PRINTS the skeleton to stdout (never overwrites an existing src file — the worker pipes/pastes it
via the edit tool, per the "workers write with edit" rule). Cites its own provenance in a header.
"""
import subprocess, sys, os, re, struct, functools

FW_BIN = "/Applications/Final Cut Pro.app/Contents/Frameworks/{fw}.framework/Versions/A/{fw}"
PROTOCOL = ["GetProgram","InitProgramDescriptor","shaderDescription","BindTexture","Bind",
            "RenderTile","RenderTile_AVX","GetDOD","GetROI","SetParameter","GetParameter","GetOutput"]

@functools.lru_cache(None)
def symmap(fw):
    out = subprocess.run(["nm","-arch","x86_64","-n",FW_BIN.format(fw=fw)],
                         capture_output=True,text=True).stdout
    syms=[]
    for l in out.splitlines():
        p=l.split()
        if len(p)>=3 and p[1] in ("T","t","W","S","s") and p[2].startswith("__Z"):
            syms.append((int(p[0],16),p[2]))
    syms.sort()
    dem = subprocess.run(["c++filt"], input="\n".join(m for _,m in syms),
                         capture_output=True,text=True).stdout.splitlines()
    return [(a,m,d) for (a,m),d in zip(syms,dem)]

def methods_of(fw, cls):
    """(addr, mangled, demangled, label) for every <cls>:: symbol, addr-sorted."""
    out=[]
    for a,m,d in symmap(fw):
        head=d.split("(",1)[0]
        if head.rsplit("::",1)[0]==cls or (("::" in head) and head.rsplit("::",1)[0].endswith(cls)):
            label=head.rsplit("::",1)[-1]
            out.append((a,m,d,label))
    return out

def vtable_addr(fw, cls):
    for a,m,d in symmap(fw):
        if d==f"vtable for {cls}": return a
    return None

def main():
    if len(sys.argv)<2: print(__doc__); return
    cls=sys.argv[1]; fw=sys.argv[2] if len(sys.argv)>2 else "Helium"
    ms=methods_of(fw,cls)
    if not ms:
        print(f"// hgc_scaffold: NO symbols for {fw} {cls}:: — check the class/framework name.")
        return
    by_label={}
    for a,m,d,label in ms: by_label.setdefault(label,[]).append((a,m,d))
    vt=vtable_addr(fw,cls)
    # ctors/dtors
    ctors=[(a,m,d) for (a,m,d,l) in ms if l==cls]
    dtors=[(a,m,d) for (a,m,d,l) in ms if l==f"~{cls}"]

    P=[]
    P.append(f"// {cls}.ts — Hgc shader-node port (framework: {fw}).")
    P.append(f"// SCAFFOLD generated by raw-port/army/tools/hgc_scaffold.py — addresses resolved from")
    P.append(f"// the {fw} symmap. Every method below is a REAL FCP symbol; fill the bodies by decoding")
    P.append(f"// each @0xADDR (disasm_class.sh {cls} {fw}) and the const-fill (resolve.py {fw} ripconst).")
    P.append(f"// Hgc protocol = HGNode subclass: GetProgram/InitProgramDescriptor/shaderDescription/")
    P.append(f"// BindTexture/Bind/RenderTile[_AVX]/GetDOD/GetROI/SetParameter/GetParameter/GetOutput.")
    if vt is not None:
        P.append(f"// vtable for {cls} @{fw} 0x{vt:x}; installed pointer (ctor stores this) = 0x{vt+0x10:x}.")
    P.append(f"//")
    P.append(f"// FULL SYMBOL MANIFEST ({len(ms)} symbols):")
    for a,m,d,l in ms:
        P.append(f"//   0x{a:<8x} {d}")
    P.append("")
    P.append('import { HGNode } from "./HGNode.js";')
    P.append("")
    P.append("/** User-writable Param slots (fill from SetParameter's idx bound check). */")
    P.append(f"export const {cls}_PARAM_COUNT = 0 as const; // TODO: read SetParameter idx guard")
    P.append("/** shaderDescription() literal — read the two movups from the .rodata literal pool. */")
    P.append(f'export const {cls}_SHADER_DESC = "{cls} [hgc1]" as const; // TODO: verify exact string in binary')
    P.append("")
    P.append(f"export class {cls} extends HGNode {{")
    # ctor
    if ctors:
        caddr=", ".join(f"@0x{a:x}" for a,_,_ in ctors)
        P.append(f"  // ctor(s): {caddr}. Const-fill the param scratch (resolve.py {fw} ripconst per movsd/movaps).")
    P.append(f"  constructor() {{")
    P.append(f"    super();")
    P.append(f'    throw new Error("{cls} ctor not yet transcribed @0x{(ctors[0][0] if ctors else 0):x}");')
    P.append(f"  }}")
    P.append("")
    for label in PROTOCOL:
        hits=by_label.get(label) or by_label.get(label.replace("_AVX",""),None)
        if label=="RenderTile_AVX":
            hits=by_label.get("RenderTile_AVX")
        if not hits:
            # find case-variant / overload
            hits=[ (a,m,d) for (a,m,d,l) in ms if l==label ]
        if not hits:
            P.append(f"  // {label}: NO symbol found in {cls}:: — may be inherited from HGNode; verify.")
            continue
        for a,m,d in hits:
            sig=d.split("(",1)[1].rstrip(")") if "(" in d else ""
            P.append(f"  // @0x{a:x}  {d}")
        a0=hits[0][0]
        P.append(f"  {label}(...args: unknown[]): unknown {{")
        P.append(f'    throw new Error("{cls}::{label} not yet transcribed @0x{a0:x}");')
        P.append(f"  }}")
        P.append("")
    # dtor note
    if dtors:
        daddr=", ".join(f"@0x{a:x}" for a,_,_ in dtors)
        P.append(f"  // dtor triple (D0/D1/D2): {daddr}. Typically reinstall vtable, Release owned child, HGNode::~HGNode, delete.")
    P.append("}")
    P.append("")
    P.append(f"// NEXT STEPS for the worker:")
    P.append(f"//  1. bash raw-port/tools/disasm_class.sh {cls} {fw}   (dumps every method above at once)")
    P.append(f"//  2. Fill ctor const-fill via: resolve.py {fw} ripconst <instr_addr> <disp> [len]")
    P.append(f"//  3. Replace each protocol stub with the transcribed body (keep the @0xADDR citation).")
    P.append(f"//  4. Widen the (...args: unknown[]) signatures to the real typed params as you port.")
    print("\n".join(P))

if __name__=="__main__": main()
