#!/usr/bin/env python3
"""Merge all decoded scope JSONs (Ozone scopes.json + scopes_<fw>.json) into src/infra/scopes.ts."""
import json, glob, os
merged={}
# Ozone (from scopes.json) + any scopes_<fw>.json
files=["raw-port/re/scopes.json"]+sorted(glob.glob("raw-port/re/scopes_*.json"))
for f in files:
    if not os.path.exists(f): continue
    d=json.load(open(f))
    for sc,tbl in d.items():
        merged.setdefault(sc,{}).update({int(k,16):v for k,v in tbl.items()})
lines=["// AUTO-GENERATED by tools/gen_scopes_ts.py from re/scopes*.json — DO NOT EDIT.",
       "// Per-scope attribute-id -> XML name tables, decoded from PCScope descriptor arrays across",
       "// Ozone + ProChannel (+ ProCore). Each scenenode/channel class's parseElement reads",
       "// attributes by integer id within its scope; this maps ids back to real XML attribute names.",
       "",
       "export type ScopeTable = Record<number, string>;",
       "export const SCOPES: Record<string, ScopeTable> = {"]
for sc in sorted(merged):
    entries=", ".join(f"{k}: {json.dumps(v)}" for k,v in sorted(merged[sc].items()))
    lines.append(f"  {json.dumps(sc)}: {{ {entries} }},")
lines += ["};","",
          "export function attrName(scope: string, id: number): string | undefined {",
          "  return SCOPES[scope]?.[id];","}"]
open("raw-port/src/infra/scopes.ts","w").write("\n".join(lines)+"\n")
print("merged scopes:",len(merged))
