#!/usr/bin/env python3
"""Build src/infra/elementTags.ts: per-scope {elementName -> typeTag} and {childName -> childScope}.
Sources: re/scope_rows.json (Ozone) + re/scope_rows_ProChannel.json if present.
An element descriptor row has id==0 and names a CHILD element of that scope with its type tag.
The child's OWN scope (for descending) is the scope named "<ElementName>Scope" or a known mapping.
"""
import json, os
rows=[]
for f in ["raw-port/re/scope_rows.json","raw-port/re/scope_rows_ProChannel.json"]:
    if os.path.exists(f): rows+=json.load(open(f))
from collections import defaultdict
byscope=defaultdict(dict)  # scope -> {name: tag}
for r in rows:
    if r.get('id')==0:
        byscope[r['scope']][r['name']]=r['tag']
lines=["// AUTO-GENERATED by tools/gen_element_tags.py from re/scope_rows*.json — DO NOT EDIT.",
       "// Per-scope child-element NAME -> element-TYPE-tag. The SAX loader assigns elem.type from",
       "// the PARENT scope's table when it opens a child element (mirrors PCSerializer getElementInfo).",
       "",
       "export const ELEMENT_TAGS: Record<string, Record<string, number>> = {"]
for sc in sorted(byscope):
    entries=", ".join(f"{json.dumps(n)}: {t}" for n,t in sorted(byscope[sc].items(), key=lambda x:x[1]))
    lines.append(f"  {json.dumps(sc)}: {{ {entries} }},")
lines+=["};","",
        "/** Type tag for a child element `name` opened within `scope` (0 if unknown). */",
        "export function elementTag(scope: string, name: string): number {",
        "  return ELEMENT_TAGS[scope]?.[name] ?? 0;",
        "}"]
open("raw-port/src/infra/elementTags.ts","w").write("\n".join(lines)+"\n")
print("scopes with element tags:",len(byscope))
for sc in ['OZSceneNodeReadScope','OZGroupScope','OZSceneScope']:
    print(" ",sc,byscope.get(sc))
