#!/usr/bin/env python3
"""verify_symidx.py — prove symidx.py is BYTE-IDENTICAL to the awk pipeline it replaces.

The index is only safe if it changes the COST of a disasm lookup and never the BYTES: every review
verdict rests on those bytes. So we diff them against ground truth.

METHOD (exhaustive, not sampled). A per-symbol check would need one full scan of the dump PER
symbol (~42s each on Flexo) — unaffordable, so it would only ever sample. Instead awk makes ONE
pass per framework and emits EVERY body in a framed stream (`###<name>\t<nbytes>` + raw bytes);
this script compares each one against the index slice. Cost is 5 scans total, and coverage is all
~45,800 symbols rather than a sample.

Ground truth is generated by AWK ITSELF, using the same boundary rule as the original command
(body = label line through the line before the next line ending in ':', first occurrence wins), so
the check does not reuse symidx's own parsing — a shared bug cannot cancel out.

    python3 verify_symidx.py [FW ...]     -> "VERIFY_SYMIDX: PASS" / "FAIL"
"""
import os, subprocess, sys, io

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import symidx

# One-pass generalization of:  awk -v s="$SYM:" '$0==s{f=1;print;next} f&&/:$/{exit} f{print}'
# Emits every symbol body once, framed with an exact byte count. LC_ALL=C makes length() count BYTES.
ONE_PASS = r'''
function flush() { if (cur != "") { printf "###%s\t%d\n", cur, nb; printf "%s", buf; cur=""; buf=""; nb=0 } }
{
  line = $0
  if (cur != "" && line ~ /:$/) flush()
  if (line ~ /^__Z[A-Za-z0-9_$.]*:$/) {
    name = substr(line, 1, length(line)-1)
    if (!(name in seen)) { seen[name]=1; cur=name; buf=line "\n"; nb=length(line)+1; next }
  }
  if (cur != "") { buf = buf line "\n"; nb += length(line)+1 }
}
END { flush() }
'''

def verify_fw(fw):
    dump = symidx.dump_path(fw)
    if not os.path.exists(dump):
        print(f"  {fw:<12} no dump — skipped"); return 0, 0
    if not symidx.fresh(fw):
        symidx.build(fw)
    env = dict(os.environ, LC_ALL="C")
    p = subprocess.Popen(["awk", ONE_PASS, dump], stdout=subprocess.PIPE, env=env, bufsize=1 << 20)
    n = bad = 0
    out = p.stdout
    while True:
        hdr = out.readline()
        if not hdr: break
        if not hdr.startswith(b"###"):
            continue
        name, _, cnt = hdr[3:].rstrip(b"\n").rpartition(b"\t")
        want_n = int(cnt)
        truth = out.read(want_n)
        buf = io.BytesIO()
        rc = symidx.slice_sym(fw, name.decode(), out=buf)
        got = buf.getvalue() if rc == 0 else b""
        n += 1
        if got != truth:
            bad += 1
            if bad <= 5:
                print(f"    MISMATCH {name.decode()[:70]}  awk={len(truth)}B idx={len(got)}B rc={rc}")
    p.wait()
    print(f"  {fw:<12} {n:>6} symbols verified  {'ALL IDENTICAL' if bad == 0 else str(bad) + ' MISMATCH'}")
    return n, bad

def main():
    fws = sys.argv[1:] or symidx.FWS
    tot = badtot = 0
    for fw in fws:
        n, b = verify_fw(fw); tot += n; badtot += b
    print()
    if badtot:
        print(f"VERIFY_SYMIDX: FAIL ❌ — {badtot}/{tot} bodies differ from the awk pipeline"); return 1
    print(f"VERIFY_SYMIDX: PASS ✅ — all {tot} symbol bodies byte-identical to the awk pipeline")
    return 0

if __name__ == "__main__":
    sys.exit(main())
