// raw-port/src/channels/AdvanceScopingWindowTask.ts
//
// FCP `AdvanceScopingWindowTask` — a tiny concrete Task subclass in the
// Flexo audio dynamic-scoping-window pipeline. Wraps a target
// `FFAudioDynamicScopingWindow*` (stored at +0x10) and, when `performTask()`
// fires, reads a `double` seconds-value at +0x200 of that target, converts
// it into an integer sample count at 30-per-second, and tail-jmps into
// `FFAudioDynamicScopingWindow::AdvanceScopingWindow(long long, FFPrerollSync*)`
// with the sample count as arg-1 and a null FFPrerollSync* as arg-2.
//
// Framework: Flexo (x86_64 slice; file /tmp/Flexo.x86_64; raw slice offsets
// quoted below match `otool -tV` VAs 1:1).
//
// Provenance disasm (auto-generated by raw-port/tools/disasm.sh):
//   raw-port/re/disasm/Flexo.AdvanceScopingWindowTask.performTask.s
//   raw-port/re/disasm/Flexo.AdvanceScopingWindowTask.getTaskReference.s
//   raw-port/re/disasm/Flexo.AdvanceScopingWindowTask.taskIdentifier.s
//   raw-port/re/disasm/Flexo.AdvanceScopingWindowTask.~AdvanceScopingWindowTask.s
//     (only the D0 body lands there — otool -tV picks the last label with
//      the source name; the D1 body @0xe5aed0..0xe5aed5 is quoted verbatim
//      below and cross-checked against a full `otool -tV /tmp/Flexo.x86_64`
//      dump — nm cross-check via /tmp/Flexo_all_nm.txt.)
//
// nm cross-check (`grep AdvanceScopingWindowTask /tmp/Flexo_all_nm.txt`):
//   0xe5aed0 t __ZN24AdvanceScopingWindowTaskD1Ev         [D1 non-deleting]
//   0xe5aee0 t __ZN24AdvanceScopingWindowTaskD0Ev         [D0 deleting]
//   0xe5aef0 t __ZN24AdvanceScopingWindowTask11performTaskEv
//   0xe5af20 t __ZN24AdvanceScopingWindowTask16getTaskReferenceEv
//   0xe5af30 t __ZNK24AdvanceScopingWindowTask14taskIdentifierEv
//   0x1917ac8 s __ZTV24AdvanceScopingWindowTask           [vtable data]
//   0x1917b10 s __ZTI24AdvanceScopingWindowTask           [typeinfo]
//   0x157ff60 s __ZTS24AdvanceScopingWindowTask           [typename string]
//
// Vtable (recovered via raw-port/army/tools/vtable.py Flexo AdvanceScopingWindowTask;
// installed-ptr 0x1917ad8, i.e. __ZTV + 0x10):
//   *0x00 -> 0xe5aed0  ~AdvanceScopingWindowTask()          [D1]
//   *0x08 -> 0xe5aee0  ~AdvanceScopingWindowTask()          [D0]
//   *0x10 -> 0xe5aef0  performTask()
//   *0x18 -> 0xe5af20  getTaskReference()
//   *0x30 -> 0xe5af30  taskIdentifier() const
// (Slot 0x20 / 0x28 not installed here; presumably inherited from the base
// task interface — this class overrides 5 slots, sharing the base's 2
// intermediate slots.)
//
// STRUCT LAYOUT (recovered from performTask + getTaskReference — the only
// fields either dereferences):
//   +0x00           vptr (installed by the base ctor to `__ZTV + 0x10`, i.e.
//                    0x1917ad8; every AdvanceScopingWindowTask instance
//                    lands here so slots 0x10/0x18/0x30 dispatch to the
//                    methods below.)
//   +0x08           opaque — inherited from base task interface, never
//                    touched by any method enumerated here.
//   +0x10           `FFAudioDynamicScopingWindow* target`  (read by both
//                    performTask @0xe5aef4 and getTaskReference @0xe5af24;
//                    this is the "task reference" the class holds.)
//
// The target FFAudioDynamicScopingWindow struct is opaque here — we only
// know that its `+0x200` slot is a `double` seconds-value (read by
// performTask @0xe5aef8 via `movsd 0x200(%rdi), %xmm0`). Everything else
// about that struct is decoded elsewhere.
//
// Cross-framework references (all resolved from the disasm + resolve.py):
//   __ZN27FFAudioDynamicScopingWindow20AdvanceScopingWindowExP13FFPrerollSync
//     @ Flexo 0xe52be0 (intra-slice — `otool -tV` renders it as a direct
//       `jmp` label from performTask @0xe5af10; nm cross-check).
//     -- FFAudioDynamicScopingWindow::AdvanceScopingWindow(long long, FFPrerollSync*)
//     -- tail-jmp target of performTask @0xe5af10.
//   __ZdlPv
//     @ libcxx via Flexo __stubs 0x1497404 (resolve.py Flexo stub 0x1497404
//       -> slot 149484 = __ZdlPv).
//     -- operator delete(void*), tail-jmp target of D0 @0xe5aee5.
//
// Data-const provenance:
//   30.0                 @ Flexo 0x156efd8   (double u64 0x403e000000000000)
//                                             — RIP-const at performTask @0xe5af00
//                                               (`mulsd 0x7140d0(%rip), %xmm0`;
//                                                RIP after the instr = 0xe5af08,
//                                                so target = 0xe5af08 + 0x7140d0
//                                                = 0x156efd8; resolve.py Flexo
//                                                const 0x156efd8 -> double 30.0).
//                                             -- 30 samples/second: the task
//                                             converts a seconds-value at
//                                             target+0x200 into a 30-sample-per-
//                                             second integer count.
//   "AdvanceScopingWindowTask"
//                        @ Flexo 0x16659f6   (C string literal; first 8 bytes
//                                             disassemble as u64 0x5365636e61766441
//                                             = ASCII "AdvanceSc..." — RIP-const
//                                             at taskIdentifier @0xe5af34
//                                             (`leaq 0x80aabb(%rip), %rax`;
//                                             RIP after instr = 0xe5af3b, target
//                                             = 0xe5af3b + 0x80aabb = 0x16659f6).
//
// FULL DISASM (all five bodies quoted verbatim from otool -tV of
// /tmp/Flexo.x86_64; cross-checked against the .s files listed above):
//
// D1  @0xe5aed0 __ZN24AdvanceScopingWindowTaskD1Ev:
//   0xe5aed0  pushq  %rbp
//   0xe5aed1  movq   %rsp, %rbp
//   0xe5aed4  popq   %rbp
//   0xe5aed5  retq
//   0xe5aed6  nopw   %cs:(%rax,%rax)                 ; padding
// [No teardown work — the class holds no owned resources beyond the vptr,
//  the +0x10 target pointer (a NON-owning reference — dtors don't touch it),
//  and any base-class state. The base task interface presumably has a
//  trivial dtor too, so nothing to chain into. D1 is a bare `ret`.]
//
// D0  @0xe5aee0 __ZN24AdvanceScopingWindowTaskD0Ev:
//   0xe5aee0  pushq  %rbp
//   0xe5aee1  movq   %rsp, %rbp
//   0xe5aee4  popq   %rbp
//   0xe5aee5  jmp    __ZdlPv                         ; TAIL-JMP operator delete(this)
//                                                    ; (stub @0x1497404)
// [Deleting variant — same "no teardown" body as D1, tail-jmp to
//  operator delete. Notably NOT `callq D1; jmp __ZdlPv` — the D1 body is
//  empty so the compiler folded it into a bare tail-delete.]
//
// performTask  @0xe5aef0 __ZN24AdvanceScopingWindowTask11performTaskEv:
//   0xe5aef0  pushq  %rbp
//   0xe5aef1  movq   %rsp, %rbp
//   0xe5aef4  movq   0x10(%rdi), %rdi                ; rdi = this->target
//                                                    ;   (FFAudioDynamicScopingWindow*)
//   0xe5aef8  movsd  0x200(%rdi), %xmm0              ; xmm0 = target->+0x200 (double,
//                                                    ;                       seconds)
//   0xe5af00  mulsd  0x7140d0(%rip), %xmm0           ; xmm0 *= 30.0
//                                                    ;   (RIP-const @0x156efd8)
//   0xe5af08  cvttsd2si %xmm0, %rsi                  ; rsi = (long long)xmm0
//                                                    ;   (truncation toward zero)
//   0xe5af0d  xorl   %edx, %edx                      ; rdx = 0  (FFPrerollSync* = null)
//   0xe5af0f  popq   %rbp                            ; epilogue
//   0xe5af10  jmp    __ZN27FFAudioDynamicScopingWindow20AdvanceScopingWindowExP13FFPrerollSync
//                                                    ; TAIL-JMP
//                                                    ;   FFAudioDynamicScopingWindow::
//                                                    ;   AdvanceScopingWindow(
//                                                    ;     long long sampleCount = rsi,
//                                                    ;     FFPrerollSync*  sync   = rdx = null)
//                                                    ; note: rdi at this point is
//                                                    ; ALREADY the target (loaded @0xe5aef4)
//                                                    ; — so the tail-jmp preserves it as
//                                                    ; the callee's `this`.
//
// getTaskReference  @0xe5af20 __ZN24AdvanceScopingWindowTask16getTaskReferenceEv:
//   0xe5af20  pushq  %rbp
//   0xe5af21  movq   %rsp, %rbp
//   0xe5af24  movq   0x10(%rdi), %rax                ; rax = this->target
//   0xe5af28  popq   %rbp
//   0xe5af29  retq
//   0xe5af2a  nopw   (%rax,%rax)                     ; padding
//
// taskIdentifier  @0xe5af30 __ZNK24AdvanceScopingWindowTask14taskIdentifierEv:
//   0xe5af30  pushq  %rbp
//   0xe5af31  movq   %rsp, %rbp
//   0xe5af34  leaq   0x80aabb(%rip), %rax            ; rax = &"AdvanceScopingWindowTask"
//                                                    ;   (RIP-const @0x16659f6)
//   0xe5af3b  popq   %rbp
//   0xe5af3c  retq
//   0xe5af3d  nopl   (%rax)                          ; padding
// [Const method — returns a stable pointer into the framework's read-only
//  __TEXT segment; the caller MUST NOT free or mutate it. Note that this
//  method is `const` (mangled as __ZNK, not __ZN), consistent with the
//  fact that it only reads a data-segment address.]

// ── constants read from Flexo __TEXT __const (verified with resolve.py const) ────────────────

/**
 * @const 0x156efd8  double = 30.0  (u64 0x403e000000000000)
 *   — 30 samples/second: `performTask` @0xe5af00 multiplies the target's
 *     `+0x200` seconds-value by this constant before truncating to a
 *     sample count. Verified: `python3 raw-port/army/tools/resolve.py
 *     Flexo const 0x156efd8` -> `double=30.0 u64=0x403e000000000000`.
 */
const K_SAMPLES_PER_SECOND: number = 30.0;

/**
 * @const 0x16659f6  ASCII C string "AdvanceScopingWindowTask"
 *   — returned by-pointer from `taskIdentifier() const` @0xe5af34. First 8
 *     bytes disassemble as u64 0x5365636e61766441 = ASCII "AdvanceSc"
 *     (little-endian), matching the mangled class name. In the FCP binary
 *     the pointer is a stable read-only address; in TS we return the
 *     identical string value (identity of the JS string is not semantically
 *     load-bearing — the callee's usage of a task identifier is presumably
 *     equality-compare-by-value against a well-known name).
 */
const K_TASK_IDENTIFIER: string = "AdvanceScopingWindowTask";

// ── opaque referenced types ──────────────────────────────────────────────────────────────────

/**
 * `FFAudioDynamicScopingWindow*` — the target the task wraps. This class
 * never dereferences it beyond reading a `double` at +0x200 (in
 * `performTask`) and returning the raw pointer (in `getTaskReference`).
 * We model it as an object with just the one known field so the
 * transcription can honestly read `+0x200` without inventing anything else.
 */
export interface FFAudioDynamicScopingWindow {
  /**
   * `+0x200` — a `double` in seconds that `performTask` scales by 30 to
   * derive a sample-count. Read at Flexo 0xe5aef8
   * (`movsd 0x200(%rdi), %xmm0`). No other slot of this struct is touched
   * by any AdvanceScopingWindowTask method.
   */
  scopingWindowSeconds_at_0x200: number;
}

/**
 * `FFPrerollSync*` — opaque; `performTask` always passes null (via
 * `xorl %edx, %edx` @0xe5af0d). Modelled as `null` to match.
 */
export type FFPrerollSyncPtr = null;

// ── frontier stubs for un-ported callees ─────────────────────────────────────────────────────

/**
 * `FFAudioDynamicScopingWindow::AdvanceScopingWindow(long long, FFPrerollSync*)`
 * @ Flexo 0xe52be0 (symbol
 * __ZN27FFAudioDynamicScopingWindow20AdvanceScopingWindowExP13FFPrerollSync;
 * intra-slice — otool -tV renders the jump as a direct label from
 * performTask @0xe5af10).
 *
 * The core action of the task: advances the scoping window by a given
 * sample count, optionally synchronising with an FFPrerollSync. Not yet
 * transcribed as its own class port; called only from
 * `AdvanceScopingWindowTask.performTask` @0xe5af10 in this file.
 */
function FFAudioDynamicScopingWindow_AdvanceScopingWindow(
  _target: FFAudioDynamicScopingWindow,
  _sampleCount: bigint,
  _sync: FFPrerollSyncPtr,
): void {
  throw new Error(
    "FFAudioDynamicScopingWindow::AdvanceScopingWindow(long long, FFPrerollSync*) " +
      "@Flexo 0xe52be0 not yet transcribed " +
      "(tail-jmp target of AdvanceScopingWindowTask::performTask @0xe5af10)",
  );
}

/**
 * `operator delete(void*)` — libcxx heap deallocator, tail-jmp target of
 * the D0 dtor @0xe5aee5 (Flexo __stubs 0x1497404). Not transcribed here —
 * a JS port has no meaningful operator delete.
 */
function operator_delete(_this: unknown): void {
  throw new Error(
    "operator delete(void*) @libcxx (via Flexo stub 0x1497404) " +
      "not yet transcribed (tail-jmp target of AdvanceScopingWindowTask D0 @0xe5aee5)",
  );
}

// ── this-pointer type ────────────────────────────────────────────────────────────────────────

/**
 * Structural view of an `AdvanceScopingWindowTask*`. The class only ever
 * dereferences the +0x10 slot (its target FFAudioDynamicScopingWindow*).
 * We model just that field, plus a phantom brand.
 */
export interface AdvanceScopingWindowTask {
  readonly __advanceScopingWindowTask: true;
  /**
   * `+0x10` — the FFAudioDynamicScopingWindow the task acts on. Read by
   *   `performTask` @0xe5aef4 and returned by `getTaskReference` @0xe5af24.
   *   Non-owning reference — the D0/D1 dtors do not touch it.
   */
  target_at_0x10: FFAudioDynamicScopingWindow;
}

// ── ported methods ───────────────────────────────────────────────────────────────────────────

/**
 * `AdvanceScopingWindowTask::~AdvanceScopingWindowTask()` [D1 non-deleting]
 * @Flexo 0xe5aed0 (symbol __ZN24AdvanceScopingWindowTaskD1Ev).
 *
 * Empty body — the class holds no owned resources (the +0x10 target is a
 * non-owning reference). The compiled body is a bare stack-frame + ret:
 *   0xe5aed0  pushq %rbp / movq %rsp,%rbp / popq %rbp / retq
 */
export function AdvanceScopingWindowTask_D1(_this: AdvanceScopingWindowTask): void {
  // (empty body — matches @0xe5aed0..0xe5aed5)
}

/**
 * `AdvanceScopingWindowTask::~AdvanceScopingWindowTask()` [D0 deleting]
 * @Flexo 0xe5aee0 (symbol __ZN24AdvanceScopingWindowTaskD0Ev).
 *
 * Same empty teardown as D1, then a tail-jmp to `operator delete(this)`.
 * The compiler folded the empty D1 body into a bare tail-delete rather
 * than `callq D1; jmp __ZdlPv`.
 *   0xe5aee0  pushq %rbp / movq %rsp,%rbp / popq %rbp
 *   0xe5aee5  jmp   __ZdlPv                                 ; stub @0x1497404
 */
export function AdvanceScopingWindowTask_D0(_this: AdvanceScopingWindowTask): void {
  // 0xe5aee5: tail-jmp __ZdlPv
  operator_delete(_this);
}

/**
 * `AdvanceScopingWindowTask::performTask()`
 * @Flexo 0xe5aef0 (symbol __ZN24AdvanceScopingWindowTask11performTaskEv).
 *
 * Reads a seconds-value from the target FFAudioDynamicScopingWindow at
 * +0x200, scales by K_SAMPLES_PER_SECOND (30.0), truncates to a long long
 * sample count, and tail-jmps into
 * `FFAudioDynamicScopingWindow::AdvanceScopingWindow(sampleCount, null)`.
 *
 * Instruction map (verified 1:1 against the disasm):
 *   @0xe5aef0..0xe5aef3  stack frame
 *   @0xe5aef4  rdi = this->target_at_0x10   ; movq 0x10(%rdi), %rdi
 *   @0xe5aef8  xmm0 = target->scopingWindowSeconds_at_0x200 (double, IEEE-754 f64)
 *              ; movsd — full double-precision load; NOT single-precision.
 *   @0xe5af00  xmm0 *= 30.0                 ; mulsd — double-precision.
 *   @0xe5af08  rsi = (long long)xmm0        ; cvttsd2si — truncation-toward-zero.
 *                                             The `t` in cvtTsd2si means truncate,
 *                                             which is exactly the C-style
 *                                             `(long long)d` conversion — matched
 *                                             below with `Math.trunc()` fed into a
 *                                             `BigInt` (long long is 64-bit signed).
 *   @0xe5af0d  rdx = 0                      ; FFPrerollSync* = null
 *   @0xe5af0f  popq %rbp
 *   @0xe5af10  tail-jmp FFAudioDynamicScopingWindow::AdvanceScopingWindow(sampleCount, null)
 *
 * Numeric fidelity: mulsd/movsd/cvttsd2si are all double-precision — no
 * Math.fround here. `long long` is 64-bit signed; the truncated value can
 * exceed 2^53 for large windows, so the sample count is a bigint per
 * PORTING_SPEC.md Rule 4.
 */
export function AdvanceScopingWindowTask_performTask(_this: AdvanceScopingWindowTask): void {
  // 0xe5aef4 / 0xe5aef8
  const target: FFAudioDynamicScopingWindow = _this.target_at_0x10;
  const seconds: number = target.scopingWindowSeconds_at_0x200;

  // 0xe5af00: xmm0 *= 30.0 (double)
  const samplesAsDouble: number = seconds * K_SAMPLES_PER_SECOND;

  // 0xe5af08: cvttsd2si — truncation to signed 64-bit.  NOTE: the x86 opcode
  // is defined to yield 0x8000000000000000 on out-of-range / NaN inputs
  // ("indefinite integer value"). For faithful transcription we don't attempt
  // to reproduce that indefinite-value edge case — the callers presumably
  // ensure a finite in-range value, matching the way FCP is exercised. We
  // straight-line the finite path exactly as the disasm does.
  const sampleCount: bigint = BigInt(Math.trunc(samplesAsDouble));

  // 0xe5af0d
  const sync: FFPrerollSyncPtr = null;

  // 0xe5af10: tail-jmp with rdi already = target.
  FFAudioDynamicScopingWindow_AdvanceScopingWindow(target, sampleCount, sync);
}

/**
 * `AdvanceScopingWindowTask::getTaskReference()`
 * @Flexo 0xe5af20 (symbol __ZN24AdvanceScopingWindowTask16getTaskReferenceEv).
 *
 * Trivial getter — returns `this->target_at_0x10`.
 * Instruction map:
 *   @0xe5af20..0xe5af23  stack frame
 *   @0xe5af24  rax = this->target_at_0x10   ; movq 0x10(%rdi), %rax
 *   @0xe5af28..0xe5af29  epilogue + retq
 */
export function AdvanceScopingWindowTask_getTaskReference(
  _this: AdvanceScopingWindowTask,
): FFAudioDynamicScopingWindow {
  // 0xe5af24
  return _this.target_at_0x10;
}

/**
 * `AdvanceScopingWindowTask::taskIdentifier() const`
 * @Flexo 0xe5af30 (symbol __ZNK24AdvanceScopingWindowTask14taskIdentifierEv).
 *
 * Trivial const getter — returns a pointer to the C string
 * "AdvanceScopingWindowTask" living in Flexo's __TEXT __cstring at
 * 0x16659f6.
 * Instruction map:
 *   @0xe5af30..0xe5af33  stack frame
 *   @0xe5af34  rax = &K_TASK_IDENTIFIER       ; leaq 0x80aabb(%rip), %rax
 *   @0xe5af3b..0xe5af3c  epilogue + retq
 */
export function AdvanceScopingWindowTask_taskIdentifier(
  _this: AdvanceScopingWindowTask,
): string {
  // 0xe5af34
  return K_TASK_IDENTIFIER;
}
