// raw-port/src/channels/getCodecGroup.ts
//
// FCP free function `getCodecGroup(unsigned int)` — collapses a codec/format
// FourCC (passed in %edi as an unsigned int) onto a canonical "group
// representative" FourCC. Several closely-related codec variants map to a
// single group id; anything not recognised is returned unchanged.
//
// Framework: Flexo (x86_64 slice). VAs below match `otool -tV` 1:1.
//
// Provenance disasm (auto-generated by raw-port/tools/disasm.sh):
//   raw-port/re/disasm/Flexo.__Z13getCodecGroupj.s   (80 lines)
//   symbol: __Z13getCodecGroupj  @0xe42290
//
// The body is a compiler-generated decision tree over the signed value of the
// argument, with three bit-test (`bt`) dispatch clusters:
//   - a 17-wide window based at 'aprh' (0x61707268) selected by mask 0x108C1;
//   - a 12-wide window based at 'apch' (0x61706368) selected by mask 0x8C1;
//   - two 64-wide windows based at 'ai12' (0x61693132) / 'ai52' (0x61693532)
//     selected by the 64-bit mask 0xC000000000000003 (and a secondary 0x18).
// plus a small 5-wide window based at 'dvh2' (0x64766832) and several direct
// FourCC equalities for the mx3/mx4/mx5 family and the ap4h/ap4x pair.
//
// FourCC decode of every immediate in the disasm (verified in-session):
//   0x61707267 aprg  0x61693531 ai51  0x61703467 ap4g  0x61693532 ai52
//   0x6d78336d mx3m  0x61707268 aprh  0x108c1 (bitmask)
//   0x6d78346f mx4o  0x6d78336e mx3n  0x6d783370 mx3p  0x6d78346e mx4n
//   0x61693132 ai12  0x61693570 ai5p  0x61706368 apch  0x8c1 (bitmask)
//   0x61703468 ap4h  0x64766832 dvh2  0x64766836 dvh6  0x18 (bitmask)
//   0x61693536 ai56  0x6d783470 mx4p  0x6d78356e mx5n  0x6d783570 mx5p
//   0x61703478 ap4x
//
// AT&T note: `cmp $imm,%edi` computes (edi - imm); `jg` = signed edi > imm,
// `jle` = signed edi <= imm, `je` = equal. The `bt`-guards use `ja`/`jae`
// (UNSIGNED) on the offset delta (`edi - base`) so the window checks are
// unsigned. The 64-bit `btq %rax,%rcx` tests bit (offset mod 64) of the mask.
//
// No in-scope callees, no externs, no indirect calls — pure integer dispatch.

/**
 * getCodecGroup(unsigned int)
 * @0xADDR Flexo 0x0000000000e42290  (__Z13getCodecGroupj)
 *
 * Faithful transcription of the 80-line decision-tree disassembly. The
 * argument is an unsigned 32-bit FourCC; the machine compares it as a SIGNED
 * int32 in the tree splits (jg/jle) — all FourCC values here are < 0x80000000
 * so signed and unsigned agree, but the sign-aware split is transcribed
 * exactly via a signed view. The `bt` window checks operate on the UNSIGNED
 * delta `(edi - base)`.
 */
export function getCodecGroup(codec: number): number {
  // %edi is an unsigned 32-bit argument.
  const edi = codec >>> 0;
  // signed int32 view for the jg/jle tree splits.
  const e = edi | 0;

  // @0xe42294  cmp $0x61707267,%edi ; @0xe4229a jg 0xe422b8 : signed edi > 'aprg'.
  if (e > 0x61707267) {
    // @0xe422b8  cmp $0x6d78336d,%edi ; jg 0xe422e0 : signed edi > 'mx3m'.
    if (e > 0x6d78336d) {
      // @0xe422e0  cmp $0x6d78346f,%edi ; jg 0xe42380 : signed edi > 'mx4o'.
      if (e > 0x6d78346f) {
        // @0xe42380 block: the mx4p/mx5n/mx5p equalities.
        // @0xe42380 cmp 'mx4p' ; je 0xe42398
        if (edi === 0x6d783470) return 0x6d78356e; // -> mx5n @0xe42398
        // @0xe42388 cmp 'mx5n' ; je 0xe42398
        if (edi === 0x6d78356e) return 0x6d78356e; // @0xe42398
        // @0xe42390 cmp 'mx5p' ; jne 0xe423af
        if (edi !== 0x6d783570) return edi; // @0xe423af eax=edi
        // @0xe42398 movl $0x6d78356e,%eax : 'mx5n'.
        return 0x6d78356e;
      }
      // @0xe422ec block: the mx3n/mx3p/mx4n equalities (edi in ('mx3m','mx4o']).
      // @0xe422ec cmp 'mx3n' ; je 0xe42398
      if (edi === 0x6d78336e) return 0x6d78356e; // @0xe42398 'mx5n'
      // @0xe422f8 cmp 'mx3p' ; je 0xe42398
      if (edi === 0x6d783370) return 0x6d78356e;
      // @0xe42304 cmp 'mx4n' ; je 0xe42398
      if (edi === 0x6d78346e) return 0x6d78356e;
      // @0xe42310 jmp 0xe423af
      return edi;
    }
    // else edi in ('aprg','mx3m]  -> the 'aprh'-based 17-wide bit window.
    // @0xe422c0 leal -0x61707268(%rdi),%ecx : ecx = edi - 'aprh' (unsigned).
    const ecx = (edi - 0x61707268) >>> 0;
    // @0xe422c6 cmp $0x10,%ecx ; ja 0xe42357 : if ecx > 0x10 -> 0xe42357.
    if (ecx > 0x10) return blk357(edi);
    // @0xe422cf movl $0x61707268,%eax ('aprh') ; @0xe422d4 movl $0x108c1,%edx ;
    // @0xe422d9 btl %ecx,%edx ; jae 0xe42357 : test bit ecx of 0x108C1.
    if (((0x108c1 >>> ecx) & 1) === 0) return blk357(edi);
    // @0xe422de retq : eax = 'aprh'.
    return 0x61707268;
  }

  // @0xe4229c cmp $0x61693531,%edi ; jle 0xe42315 : signed edi <= 'ai51'.
  if (e <= 0x61693531) {
    // @0xe42315 leal -0x61693132(%rdi),%eax : eax = edi - 'ai12' (unsigned).
    const eax = (edi - 0x61693132) >>> 0;
    // @0xe4231b shared tail (see blk31b): 64-wide masked window.
    return blk31b(edi, eax);
  }

  // @0xe422a4 cmp $0x61703467,%edi ; jg 0xe4233b : signed edi > 'ap4g'.
  if (e > 0x61703467) {
    // @0xe4233b leal -0x61706368(%rdi),%eax : eax = edi - 'apch' (unsigned).
    const eax = (edi - 0x61706368) >>> 0;
    // @0xe42341 cmp $0xb,%eax ; ja 0xe4239f : if eax > 0xb -> 0xe4239f.
    if (eax > 0xb) return blk39f(edi);
    // @0xe42346 movl $0x8c1,%ecx ; btl %eax,%ecx ; jae 0xe4239f.
    if (((0x8c1 >>> eax) & 1) === 0) return blk39f(edi);
    // @0xe42350 movl $0x61703468,%eax : 'ap4h'.
    return 0x61703468;
  }

  // @0xe422b0 leal -0x61693532(%rdi),%eax ; jmp 0xe4231b :
  //   the OTHER predecessor of the shared 64-wide tail — base is 'ai52'.
  {
    const eax = (edi - 0x61693532) >>> 0;
    return blk31b(edi, eax);
  }
}

/**
 * Shared tail at @0xe4231b (reached from @0xe42315 with base 'ai12' and from
 * @0xe422b0 with base 'ai52'). `eax` is the caller-computed unsigned offset.
 */
function blk31b(edi: number, eax: number): number {
  // @0xe4231b cmp $0x3f,%eax ; ja 0xe423af : offset > 63 -> return edi.
  if (eax > 0x3f) return edi; // @0xe423af eax=edi
  // @0xe42324 movabsq $-0x3ffffffffffffffd,%rcx  (= 0xC000000000000003) ;
  // @0xe4232e btq %rax,%rcx ; jae 0xe4236e : test bit eax of the 64-bit mask.
  const MASK = 0xc000000000000003n;
  if (((MASK >> BigInt(eax)) & 1n) === 0n) {
    // @0xe4236e movl $0x18,%ecx ; btq %rax,%rcx ; jae 0xe423af.
    if (((0x18 >>> eax) & 1) === 0) return edi; // @0xe423af
    // @0xe42379 movl $0x61693536,%eax : 'ai56'.
    return 0x61693536;
  }
  // @0xe42334 movl $0x61693570,%eax : 'ai5p'.
  return 0x61693570;
}

/**
 * Sub-window at @0xe42357: the 'dvh2'-based 5-wide window (excluding offset 2),
 * mapping to 'dvh6'.
 */
function blk357(edi: number): number {
  // @0xe42357 leal -0x64766832(%rdi),%eax : eax = edi - 'dvh2' (unsigned).
  const eax = (edi - 0x64766832) >>> 0;
  // @0xe4235d cmp $0x4,%eax ; ja 0xe423af : offset > 4 -> return edi.
  if (eax > 0x4) return edi; // @0xe423af
  // @0xe42362 cmp $0x2,%eax ; je 0xe423af : offset == 2 -> return edi.
  if (eax === 0x2) return edi;
  // @0xe42367 movl $0x64766836,%eax : 'dvh6'.
  return 0x64766836;
}

/**
 * Sub-block at @0xe4239f: the ap4h/ap4x equalities, else return unchanged.
 */
function blk39f(edi: number): number {
  // @0xe4239f cmp $0x61703468,%edi ; je 0xe42350 : 'ap4h' -> 'ap4h'.
  if (edi === 0x61703468) return 0x61703468; // @0xe42350
  // @0xe423a7 cmp $0x61703478,%edi ; je 0xe42350 : 'ap4x' -> 'ap4h'.
  if (edi === 0x61703478) return 0x61703468;
  // @0xe423af eax=edi.
  return edi;
}
