// OZChannelQuad_Factory — ProChannel factory singleton for OZChannelQuad.
//
// Transcribed from /Applications/Final Cut Pro.app/Contents/Frameworks/
// ProChannel.framework/Versions/A/ProChannel (x86_64 slice; unadjusted
// VAs from `otool -tV`). Disassembly source:
//   raw-port/re/disasm/ProChannel.__ZN21OZChannelQuad_Factory11getInstanceEv.s
//
// This unit ports ONLY the `getInstance()` static singleton accessor at
// @0x1e88. The remaining methods on this factory (C2/D1/D0/create*/
// createChannel*/... etc.) are separate ledger entries and are OUT OF
// SCOPE for this file — per the "one class per file" rule they will be
// added to this same class file when their own ledger entries are
// claimed by future depclaim rounds.
//
// This file follows the SAME structural pattern as OZChannelBase_Factory
// (a sibling in raw-port/src/channels/) — every FCP factory singleton
// generated by the ProChannel PCSingleton framework compiles to a
// byte-for-byte identical getInstance() skeleton, differing only in the
// global BSS symbols and the templated call_once_proxy instantiation.
//
// -----------------------------------------------------------------------------
// PROCESS-GLOBAL STORAGE
// -----------------------------------------------------------------------------
//   __ZN21OZChannelQuad_Factory13_instanceOnceE
//     — libc++ std::once_flag (unsigned long). 0 = not started;
//       -1 (~0UL) = init complete. Fast-path @0x1e9a compares to $-1.
//   __ZN21OZChannelQuad_Factory9_instanceE
//     — OZChannelQuad_Factory*. Written by the __call_once_proxy lambda,
//       read by getInstance @0x1ec5.
//
// -----------------------------------------------------------------------------
// FRONTIER CALLEES (all TRUE OUT-OF-SCOPE externs or SEPARATE ledger units)
// -----------------------------------------------------------------------------
//   * __ZNSt3__111__call_onceERVmPvPFvS2_E
//       — std::__1::__call_once(flag&, void*, void(*)(void*))
//       — libc++ (libc++.dylib) — TRUE out-of-scope extern. Called
//         @0x1ec0 via ProChannel stub 0xacdc8. Same policy as
//         HGMemory's call_once callsites and OZChannelBase_Factory
//         (see raw-port/src/channels/OZChannelBase_Factory.ts).
//
//   * __ZNSt3__117__call_once_proxyB9nqe210106<
//         tuple<OZChannelQuad_Factory::getInstance()::'lambda'()&&>>(void*)
//       — libc++ template instantiation. NOT called directly by
//         getInstance — passed as the `void(*)(void*)` argument to
//         __call_once. Its body is `jmp __invoke<...>` at ProChannel
//         (a separate ledger entry NOT in this file's scope). The
//         __invoke instantiation @ProChannel 0x80876 does:
//             1. operator new(0x88)   @0x80882 (imported __Znwm 0xace4c)
//             2. OZChannelQuad_FactoryC2Ev @0x8088d (ledger: todo)
//             3. _instance = new_ptr  @0x80892
//         with a landing pad @0x8089e that operator-delete-and-
//         __Unwind_Resume's on C2 throw. All of that is a SEPARATE
//         ledger unit; here we throw a citing frontier stub for it.
//
// -----------------------------------------------------------------------------
// Symbols ported here (mangled → address)
// -----------------------------------------------------------------------------
//   * __ZN21OZChannelQuad_Factory11getInstanceEv
//       — OZChannelQuad_Factory::getInstance() @ProChannel 0x1e88
//
// -----------------------------------------------------------------------------
// FULL DISASM (raw-port/re/disasm/ProChannel.__ZN21OZChannelQuad_Factory11getInstanceEv.s)
// -----------------------------------------------------------------------------
//   0x1e88  pushq  %rbp                              ; frame prologue
//   0x1e89  movq   %rsp, %rbp
//   0x1e8c  subq   $0x20, %rsp                       ; 32-byte local frame
//                                                    ; (holds a 3-word libc++
//                                                    ; tuple<lambda&&> plus
//                                                    ; alignment padding)
//   0x1e90  leaq   _instanceOnce(%rip), %rax         ; rax = &_instanceOnce
//   0x1e97  movq   (%rax), %rax                      ; rax = _instanceOnce
//   0x1e9a  cmpq   $-0x1, %rax                       ; already-init check
//                                                    ; (libc++ writes ~0UL on
//                                                    ; completion)
//   0x1e9e  je     0x1ec5                            ; fast path: skip call_once
//   0x1ea0  leaq   -0x1(%rbp), %rax                  ; rax = 1-byte captureless
//                                                    ; lambda slot on the stack
//   0x1ea4  leaq   -0x18(%rbp), %rcx                 ; rcx = tuple<T&&> slot
//   0x1ea8  movq   %rax, (%rcx)                      ; tuple.head = &lambda-slot
//   0x1eab  leaq   -0x10(%rbp), %rsi                 ; rsi = call_once's void* arg slot
//   0x1eaf  movq   %rcx, (%rsi)                      ; *arg = &tuple
//   0x1eb2  leaq   _instanceOnce(%rip), %rdi         ; rdi = &_instanceOnce
//   0x1eb9  leaq   __call_once_proxy<...>(%rip), %rdx; rdx = &proxy_func
//   0x1ec0  callq  std::__call_once                   ; libc++ stub @0xacdc8
//                                                    ; signature:
//                                                    ;  (once_flag& = %rdi,
//                                                    ;   void* arg   = %rsi,
//                                                    ;   void(*)(void*) = %rdx)
//   0x1ec5  leaq   _instance(%rip), %rax             ; rax = &_instance
//   0x1ecc  movq   (%rax), %rax                      ; rax = _instance (return value)
//   0x1ecf  addq   $0x20, %rsp                       ; epilogue
//   0x1ed3  popq   %rbp
//   0x1ed4  retq

// ═════════════════════════════════════════════════════════════════════════
// Process-global BSS slots — one 8-byte word each, sitting at fixed
// linker-assigned addresses in ProChannel's __common/__bss. TS has no
// linker, so we model them as module-scope `let`s (zero-filled at load,
// matching Mach-O convention).
// ═════════════════════════════════════════════════════════════════════════

/** @ProChannel BSS `__ZN21OZChannelQuad_Factory13_instanceOnceE`.
 *  libc++ std::once_flag word. 0n = not started; -1n = completed.
 *  getInstance's fast-path check `cmpq $-1, %rax` @0x1e9a. */
let _instanceOnce: bigint = 0n; // @ProChannel BSS 0x1e88 read-site

/** @ProChannel BSS `__ZN21OZChannelQuad_Factory9_instanceE`.
 *  The singleton pointer. Read @0x1ec5-0x1ecc (return value).
 *  Written by the __call_once_proxy lambda's __invoke instantiation
 *  @ProChannel 0x80892. */
let _instance: OZChannelQuad_Factory | null = null; // @ProChannel BSS 0x1ec5

/**
 * `std::__1::__call_once(flag&, void* arg, void(*)(void*))` — libc++.
 * Called from getInstance @0x1ec0 via ProChannel stub 0xacdc8. TRUE
 * out-of-scope extern (libc++ runtime). Modelled here as the minimum
 * behaviour getInstance observes: on first invocation with a zero
 * once_flag, invoke proxy(arg); on success mark the flag ~0. If proxy
 * throws, the flag stays 0 and future calls will retry. Single-
 * threaded (no atomic CAS) — accurate for the JS execution model. */
function std_call_once(
  once: { get(): bigint; set(v: bigint): void },
  arg: unknown,
  proxy: (arg: unknown) => void,
): void {
  // libc++ fast-path (also open-coded in the caller @0x1e9a).
  if (once.get() === -1n) return;
  proxy(arg);
  once.set(-1n);
}

/**
 * `__ZNSt3__117__call_once_proxy<...>` — libc++ template instantiation
 * whose body is `jmp __ZNSt3__18__invoke<...>` at ProChannel 0x80876.
 * That __invoke @ProChannel 0x80876..0x8089d does:
 *
 *   0x80877  push rbp / mov rbp,rsp / push r14 / push rbx
 *   0x8087d  movl  $0x88, %edi                     ; size = 0x88
 *   0x80882  callq operator new                    ; __Znwm stub 0xace4c
 *   0x80887  movq  %rax, %rbx                      ; rbx = raw ptr
 *   0x8088a  movq  %rax, %rdi
 *   0x8088d  callq __ZN21OZChannelQuad_FactoryC2Ev ; C2 ctor (ledger: todo)
 *   0x80892  movq  %rbx, _instance(%rip)           ; _instance = raw ptr
 *   0x80899  epilogue
 *   -- landing pad @0x8089e --
 *   0x8089e  movq  %rax, %r14                      ; save exception handle
 *   0x808a1  movq  %rbx, %rdi
 *   0x808a4  callq operator delete                 ; __ZdlPv stub 0xace04
 *   0x808a9  movq  %r14, %rdi
 *   0x808ac  callq __Unwind_Resume                 ; stub 0xacaf2
 *
 * Neither `operator new` (__Znwm stub 0xace4c) nor the C2 ctor
 * (__ZN21OZChannelQuad_FactoryC2Ev, ledger status: todo) is yet
 * ported — this __invoke instantiation is a SEPARATE ledger unit and
 * will be filled in when it is next claimed. We stub it with an error
 * that cites every deferred call site. */
function __call_once_proxy_getInstance_lambda(_arg: unknown): void {
  throw new Error(
    "OZChannelQuad_Factory::getInstance() __call_once init lambda not yet " +
      "transcribed — the lambda body @ProChannel 0x80876 allocates 0x88 " +
      "bytes via operator new @0x80882 (imported __Znwm 0xace4c) then " +
      "invokes __ZN21OZChannelQuad_FactoryC2Ev @ProChannel 0x8088d (C2 " +
      "base ctor, ledger status: todo) and stores the result into " +
      "_instance @0x80892. Neither operator new nor the C2 ctor is yet " +
      "ported — this lambda function is a SEPARATE ledger unit and will " +
      "be filled in when it is next claimed. The proxy is invoked from " +
      "std::__call_once at ProChannel 0x1ec0.",
  );
}

// ═════════════════════════════════════════════════════════════════════════
// The class
// ═════════════════════════════════════════════════════════════════════════

/**
 * `OZChannelQuad_Factory` — factory singleton for OZChannelQuad channel
 * instances. Only its getInstance() accessor is ported in this file;
 * every other method is a separate ledger entry. Per the operator-new
 * call in the init lambda @0x8087d, the concrete instance is 0x88 bytes
 * — field offsets are not yet decoded since only getInstance is
 * transcribed here.
 */
export class OZChannelQuad_Factory {
  /**
   * `OZChannelQuad_Factory::getInstance()` — @ProChannel 0x1e88
   * (__ZN21OZChannelQuad_Factory11getInstanceEv).
   *
   * Faithful line-for-line transcription of the disassembly quoted in
   * the file header. Standard libc++ std::call_once-guarded singleton
   * accessor. Structurally identical to
   * OZChannelBase_Factory::getInstance @0x1786; only the referenced
   * globals and the templated proxy differ.
   *
   *   1. Read _instanceOnce; if equal to $-1 (libc++ "init complete"
   *      sentinel), skip to step 3 (fast path @0x1e9a-0x1e9e).
   *
   *   2. Set up libc++'s ABI tuple<lambda&&> on the stack (an empty
   *      captureless lambda -> tuple.head -> void* arg) and call
   *      std::__call_once(&_instanceOnce, arg, proxy) @0x1eb2-0x1ec0.
   *      The proxy invokes the __invoke instantiation which allocates
   *      0x88 bytes, C2-constructs the singleton, and writes it to
   *      _instance.
   *
   *   3. Return _instance @0x1ec5-0x1ecc.
   *
   * The stack tuple + captureless-lambda dance @0x1ea0..0x1eaf is an
   * ABI-level artefact of libc++'s __call_once template instantiation
   * (the caller side just does "call call_once with the proxy pointer"
   * and doesn't observe the intermediate slots). In this port we model
   * std_call_once directly, passing null for the arg — the proxy
   * doesn't need the tuple pointer because our proxy is a JS closure
   * without a captureless-lambda address. Observable behaviour matches.
   */
  static getInstance(): OZChannelQuad_Factory | null {
    // ------------------------------------------------------------
    // @0x1e88..0x1e8c — prologue + 0x20-byte local frame (no effect).
    // @0x1e90..0x1e97 — rax = _instanceOnce.
    // @0x1e9a..0x1e9e — if (_instanceOnce == -1) goto fast_path (0x1ec5).
    // ------------------------------------------------------------
    if (_instanceOnce !== -1n) {
      // ------------------------------------------------------------
      // @0x1ea0..0x1eaf — set up libc++ tuple<lambda&&> on the stack.
      //   (ABI marshaling — no TS-visible effect; our proxy is a JS
      //    closure that doesn't unpack the tuple.)
      // @0x1eb2 — rdi = &_instanceOnce.
      // @0x1eb9 — rdx = &__call_once_proxy<...>.
      // @0x1ec0 — callq std::__call_once (libc++ stub @0xacdc8).
      // ------------------------------------------------------------
      std_call_once(
        {
          get: (): bigint => _instanceOnce,
          set: (v: bigint): void => {
            _instanceOnce = v;
          },
        },
        null, // ABI void* — disasm passes &tuple; our proxy ignores it.
        __call_once_proxy_getInstance_lambda,
      );
    }
    // ------------------------------------------------------------
    // @0x1ec5..0x1ecc — rax = _instance.
    // @0x1ecf..0x1ed4 — epilogue + retq.
    // ------------------------------------------------------------
    return _instance;
  }
}
