// raw-port/src/channels/OZPlaybackEngine.ts
//
// FCP `OZPlaybackEngine` — a tiny 8-byte POD value-type wrapping an
// `OZPlaybackEngineType` enum plus a 4-byte flags/aux field. Every method
// enumerated in the ledger is a compiler-generated / hand-written value-type
// primitive: 2 default ctors, 2 enum-taking ctors, 2 copy ctors, one
// assignment operator, one equality operator. NO virtual methods, NO vtable,
// NO typeinfo symbol (verified: `grep ZTV16OZPlaybackEngine
// /tmp/Ozone_allsyms.txt` returns nothing) — so `OZPlaybackEngine` is not a
// polymorphic type. It is a value struct passed by value or by reference,
// and its methods are non-virtual by definition.
//
// This is a REAL (albeit trivial) piece of math — the equality operator
// mirrors the exact two-field compare the compiler emitted, the assignment
// operator preserves the self-check-then-copy fast-path, and the enum-ctor
// initialises +0x4 to zero even though only +0x0 receives the caller's
// argument. Getting any of those wrong (e.g. omitting the self-check, or
// zeroing +0x4 in the default ctor via `movl` twice instead of one `movq`)
// would silently diverge from the binary.
//
// Framework: Ozone (x86_64 slice; file /tmp/Ozone.x86_64; VAs quoted below
// match `otool -tV` output 1:1).
//
// Provenance disasm (auto-generated by raw-port/tools/disasm.sh — Ozone is
// the default framework, so files land WITHOUT an "Ozone." prefix):
//   raw-port/re/disasm/OZPlaybackEngine.OZPlaybackEngine.s
//     (only C1E20OZPlaybackEngineType lands there — disasm.sh returns the
//      first symbol matching `OZPlaybackEngine::OZPlaybackEngine(`; the
//      other 5 ctor bodies were extracted via a full otool -tV dump and
//      quoted verbatim below.)
//   raw-port/re/disasm/OZPlaybackEngine.operator=.s
//   raw-port/re/disasm/OZPlaybackEngine.operator==.s
//
// nm cross-check (`grep OZPlaybackEngine /tmp/Ozone_allsyms.txt`):
//   0x26ff50 T __ZN16OZPlaybackEngineC2Ev                    [C2 default]
//   0x26ff60 T __ZN16OZPlaybackEngineC1Ev                    [C1 default]
//   0x26ff70 T __ZN16OZPlaybackEngineC2E20OZPlaybackEngineType  [C2 enum]
//   0x26ff80 T __ZN16OZPlaybackEngineC1E20OZPlaybackEngineType  [C1 enum]
//   0x26ff90 T __ZN16OZPlaybackEngineC2ERKS_                  [C2 copy]
//   0x26ffa0 T __ZN16OZPlaybackEngineC1ERKS_                  [C1 copy]
//   0x26ffb0 T __ZN16OZPlaybackEngineaSERKS_                  [operator=]
//   0x26ffd0 T __ZNK16OZPlaybackEngineeqERKS_                 [operator== const]
// (No __ZTV / __ZTI / __ZTS symbols — non-polymorphic type.)
//
// nm cross-check for ICF folding: C2Ev @0x26ff50 and C1Ev @0x26ff60 sit at
// DIFFERENT VAs (16-byte gap = 0x10) with IDENTICAL bodies (both `pushq;
// movq %rsp,%rbp; movq $0x0,(%rdi); popq %rbp; retq`). ICF is not
// happening here — the linker preserved both bodies. Similarly the C1/C2
// pairs for the enum-ctor (0x26ff70 vs 0x26ff80) and copy-ctor
// (0x26ff90 vs 0x26ffa0) are byte-identical but distinct.
//
// STRUCT LAYOUT (recovered from all 8 method bodies — every field access
// is documented below with the reading address):
//
//   size = 8 bytes  (the default ctor writes `movq $0, (%rdi)` @0x26ff54,
//                    zeroing 8 bytes in one store; the enum-ctor writes
//                    `movl %esi, (%rdi)` + `movl $0, 4(%rdi)`, filling the
//                    same 8 bytes with two 4-byte stores; the copy-ctor
//                    reads/writes 8 bytes as one movq; operator== compares
//                    two 4-byte halves at +0x0 and +0x4).
//
//   +0x00  u32  type   (OZPlaybackEngineType enum — the caller's arg to
//                       the enum-ctor lands here @0x26ff74/0x26ff84
//                       `movl %esi, (%rdi)`; read by operator== @0x26ffd4
//                       `movl (%rdi), %eax`).
//   +0x04  u32  flags  (auxiliary; zeroed by both the default-ctor
//                       (as part of the 8-byte zero @0x26ff54) and the
//                       enum-ctor (explicit `movl $0, 4(%rdi)` @0x26ff76),
//                       and read by operator== @0x26ffda
//                       `movl 4(%rdi), %eax`. NOT written by the copy-ctor
//                       or operator= separately — those move 8 bytes as a
//                       unit via one movq).
//
// The reason flags is written EXPLICITLY as 0 in the enum-ctor (rather
// than as part of a movq $0) is that the compiler laid the ctor out as
// two aligned 32-bit stores: the first uses the argument register
// (`movl %esi, ...`) so the second must also be 32-bit for locality.
// The default-ctor could freely coalesce both into `movq $0`.
//
// Cross-framework references (all resolved from the disasm):
//   NONE. This class is fully self-contained: no external callees, no
//   __stubs entries, no data-const reads, no vtable slots. Every
//   instruction body ends with a plain `retq`.
//
// FULL DISASM (all 8 bodies quoted verbatim from otool -tV of
// /tmp/Ozone.x86_64; C2 bodies were extracted via
// `otool -tV /tmp/Ozone.x86_64 -p __ZN16OZPlaybackEngineC2Ev`):
//
// C2 default  @0x26ff50 __ZN16OZPlaybackEngineC2Ev:
//   0x26ff50  pushq  %rbp
//   0x26ff51  movq   %rsp, %rbp
//   0x26ff54  movq   $0x0, (%rdi)            ; *(u64*)this = 0  (zeroes both fields)
//   0x26ff5b  popq   %rbp
//   0x26ff5c  retq
//   0x26ff5d  nopl   (%rax)                  ; padding
//
// C1 default  @0x26ff60 __ZN16OZPlaybackEngineC1Ev:
//   0x26ff60  pushq  %rbp
//   0x26ff61  movq   %rsp, %rbp
//   0x26ff64  movq   $0x0, (%rdi)            ; *(u64*)this = 0
//   0x26ff6b  popq   %rbp
//   0x26ff6c  retq
//   0x26ff6d  nopl   (%rax)                  ; padding
//
// C2 enum  @0x26ff70 __ZN16OZPlaybackEngineC2E20OZPlaybackEngineType:
//   0x26ff70  pushq  %rbp
//   0x26ff71  movq   %rsp, %rbp
//   0x26ff74  movl   %esi, (%rdi)            ; this->type_at_0x0 = arg (u32)
//   0x26ff76  movl   $0x0, 0x4(%rdi)         ; this->flags_at_0x4 = 0
//   0x26ff7d  popq   %rbp
//   0x26ff7e  retq
//   0x26ff7f  nop                            ; padding
//
// C1 enum  @0x26ff80 __ZN16OZPlaybackEngineC1E20OZPlaybackEngineType:
//   0x26ff80  pushq  %rbp
//   0x26ff81  movq   %rsp, %rbp
//   0x26ff84  movl   %esi, (%rdi)            ; this->type_at_0x0 = arg (u32)
//   0x26ff86  movl   $0x0, 0x4(%rdi)         ; this->flags_at_0x4 = 0
//   0x26ff8d  popq   %rbp
//   0x26ff8e  retq
//   0x26ff8f  nop                            ; padding
//
// C2 copy  @0x26ff90 __ZN16OZPlaybackEngineC2ERKS_:
//   0x26ff90  pushq  %rbp
//   0x26ff91  movq   %rsp, %rbp
//   0x26ff94  movq   (%rsi), %rax            ; rax = *(u64*)other  (both fields as one word)
//   0x26ff97  movq   %rax, (%rdi)            ; *(u64*)this = rax
//   0x26ff9a  popq   %rbp
//   0x26ff9b  retq
//   0x26ff9c  nopl   (%rax)                  ; padding
//
// C1 copy  @0x26ffa0 __ZN16OZPlaybackEngineC1ERKS_:
//   0x26ffa0  pushq  %rbp
//   0x26ffa1  movq   %rsp, %rbp
//   0x26ffa4  movq   (%rsi), %rax            ; rax = *(u64*)other
//   0x26ffa7  movq   %rax, (%rdi)            ; *(u64*)this = rax
//   0x26ffaa  popq   %rbp
//   0x26ffab  retq
//   0x26ffac  nopl   (%rax)                  ; padding
//
// operator=  @0x26ffb0 __ZN16OZPlaybackEngineaSERKS_:
//   0x26ffb0  pushq  %rbp
//   0x26ffb1  movq   %rsp, %rbp
//   0x26ffb4  movq   %rdi, %rax              ; rax = this      (return value)
//   0x26ffb7  cmpq   %rsi, %rdi              ; if (this == &other)
//   0x26ffba  je     0x26ffc2                ;   skip copy — self-assignment fast path
//   0x26ffbc  movq   (%rsi), %rcx            ; rcx = *(u64*)other
//   0x26ffbf  movq   %rcx, (%rax)            ; *(u64*)this = rcx   (rax==rdi==this)
//   0x26ffc2  popq   %rbp
//   0x26ffc3  retq
//   0x26ffc4  nopw   %cs:(%rax,%rax)         ; padding
//
// operator== const  @0x26ffd0 __ZNK16OZPlaybackEngineeqERKS_:
//   0x26ffd0  pushq  %rbp
//   0x26ffd1  movq   %rsp, %rbp
//   0x26ffd4  movl   (%rdi), %eax            ; eax = this->type_at_0x0
//   0x26ffd6  cmpl   (%rsi), %eax            ; compare with other->type_at_0x0
//   0x26ffd8  jne    0x26ffe5                ; if not equal -> return false
//   0x26ffda  movl   0x4(%rdi), %eax         ; eax = this->flags_at_0x4
//   0x26ffdd  cmpl   0x4(%rsi), %eax         ; compare with other->flags_at_0x4
//   0x26ffe0  sete   %al                     ; al = (flags equal) ? 1 : 0  (zero-extended
//                                            ;                              on return via ABI)
//   0x26ffe3  popq   %rbp
//   0x26ffe4  retq
//   0x26ffe5  xorl   %eax, %eax              ; return 0 (types differ)
//   0x26ffe7  popq   %rbp
//   0x26ffe8  retq
//   0x26ffe9  nopl   (%rax)                  ; padding
//
// Note the ABI quirk on operator==: the `sete %al` path ONLY sets the low
// byte of rax, leaving the high 56 bits UNDEFINED at the instruction
// level. The System V AMD64 ABI defines `bool` as a zero-extended byte
// return, and the compiler here relies on the caller to only read the
// low byte — the `sete` path is correct precisely because the ABI says so.
// The `xorl %eax, %eax` path explicitly zeros the full rax. From the
// caller's perspective both paths yield a well-defined `bool`.

// ── the value type ───────────────────────────────────────────────────────────────────────────

/**
 * `OZPlaybackEngineType` — the u32 enum stored at OZPlaybackEngine +0x0.
 * Not enumerated here (the specific enum values are not read from any
 * method in this class — every access treats the field as an opaque u32
 * compared for equality). We type it as `number` (u32-shaped) to match
 * the ABI: the enum-ctor receives it in `%esi` @0x26ff74/0x26ff84, a
 * 32-bit-wide register. Downstream code that owns the enum values
 * (whichever class defines them) should re-export a stricter type.
 */
export type OZPlaybackEngineType = number;

/**
 * `OZPlaybackEngine` — 8-byte POD value type (see STRUCT LAYOUT above).
 * We mirror the exact 2-field layout the compiler used; every method
 * below reads/writes these two fields with the same offsets as the
 * disasm.
 */
export interface OZPlaybackEngine {
  /**
   * `+0x00` — u32 enum. Written by:
   *   - default ctors @0x26ff54 / 0x26ff64 (via `movq $0`, half of the qword)
   *   - enum ctors    @0x26ff74 / 0x26ff84 (`movl %esi, (%rdi)`)
   *   - copy ctors    @0x26ff97 / 0x26ffa7 (via `movq`, half of the qword)
   *   - operator=     @0x26ffbf (via `movq`, half of the qword)
   * Read by:
   *   - operator==    @0x26ffd4 (`movl (%rdi), %eax`)
   */
  type_at_0x0: OZPlaybackEngineType;
  /**
   * `+0x04` — u32 aux/flags. Written by:
   *   - default ctors @0x26ff54 / 0x26ff64 (via `movq $0`, half of the qword)
   *   - enum ctors    @0x26ff76 / 0x26ff86 (`movl $0, 4(%rdi)`)
   *   - copy ctors    @0x26ff97 / 0x26ffa7 (via `movq`, half of the qword)
   *   - operator=     @0x26ffbf (via `movq`, half of the qword)
   * Read by:
   *   - operator==    @0x26ffda (`movl 4(%rdi), %eax`)
   */
  flags_at_0x4: number;
}

// ── ported methods ───────────────────────────────────────────────────────────────────────────

/**
 * `OZPlaybackEngine::OZPlaybackEngine()` [C2 = C1 default ctor]
 * @Ozone 0x26ff50 (__ZN16OZPlaybackEngineC2Ev) — same body at 0x26ff60
 * (__ZN16OZPlaybackEngineC1Ev).
 *
 * Zeroes both fields with a single 8-byte store (`movq $0x0, (%rdi)`
 * @0x26ff54 / 0x26ff64).
 */
export function OZPlaybackEngine_default_ctor(this_: OZPlaybackEngine): void {
  // 0x26ff54: movq $0x0, (%rdi)  — zeroes both fields in one shot.
  this_.type_at_0x0 = 0;
  this_.flags_at_0x4 = 0;
}

/**
 * `OZPlaybackEngine::OZPlaybackEngine(OZPlaybackEngineType)` [C2 = C1 enum ctor]
 * @Ozone 0x26ff70 (__ZN16OZPlaybackEngineC2E20OZPlaybackEngineType) —
 * same body at 0x26ff80 (__ZN16OZPlaybackEngineC1E20OZPlaybackEngineType).
 *
 * Sets `type_at_0x0` to the caller's argument (`movl %esi, (%rdi)`
 * @0x26ff74 / 0x26ff84) and explicitly zeros `flags_at_0x4`
 * (`movl $0x0, 0x4(%rdi)` @0x26ff76 / 0x26ff86) — the two separate
 * 32-bit stores that the compiler emitted (not coalesced into a movq
 * because one operand is a register).
 */
export function OZPlaybackEngine_ctor_type(
  this_: OZPlaybackEngine,
  type: OZPlaybackEngineType,
): void {
  // 0x26ff74 / 0x26ff84: movl %esi, (%rdi)
  this_.type_at_0x0 = type;
  // 0x26ff76 / 0x26ff86: movl $0x0, 0x4(%rdi)
  this_.flags_at_0x4 = 0;
}

/**
 * `OZPlaybackEngine::OZPlaybackEngine(OZPlaybackEngine const&)` [C2 = C1 copy ctor]
 * @Ozone 0x26ff90 (__ZN16OZPlaybackEngineC2ERKS_) — same body at
 * 0x26ffa0 (__ZN16OZPlaybackEngineC1ERKS_).
 *
 * Copies both fields as one 64-bit word (`movq (%rsi), %rax` @0x26ff94 /
 * 0x26ffa4; `movq %rax, (%rdi)` @0x26ff97 / 0x26ffa7). No self-check
 * (the copy-ctor is only ever called at object construction, when the
 * source and dest are guaranteed distinct).
 */
export function OZPlaybackEngine_copy_ctor(
  this_: OZPlaybackEngine,
  other: OZPlaybackEngine,
): void {
  // 0x26ff94 / 0x26ffa4: movq (%rsi), %rax
  // 0x26ff97 / 0x26ffa7: movq %rax, (%rdi)
  this_.type_at_0x0 = other.type_at_0x0;
  this_.flags_at_0x4 = other.flags_at_0x4;
}

/**
 * `OZPlaybackEngine::operator=(OZPlaybackEngine const&)`
 * @Ozone 0x26ffb0 (__ZN16OZPlaybackEngineaSERKS_).
 *
 * Copy-assignment with the classic self-assignment fast-path guard:
 *   if (this == &other) return *this;
 *   *(u64*)this = *(u64*)&other;
 *   return *this;
 *
 * The 8-byte block copy is emitted via a single movq load + store
 * (@0x26ffbc `movq (%rsi), %rcx`; @0x26ffbf `movq %rcx, (%rax)` where
 * rax == this saved @0x26ffb4). Returns `this` — matching the ABI where
 * the return value in rax was pre-populated @0x26ffb4 with `movq %rdi,
 * %rax` BEFORE the compare, so both branches (self-assign and copy)
 * exit with rax == this.
 */
export function OZPlaybackEngine_operator_assign(
  this_: OZPlaybackEngine,
  other: OZPlaybackEngine,
): OZPlaybackEngine {
  // 0x26ffb4: movq %rdi, %rax  — return value = this (pre-populated).
  // 0x26ffb7: cmpq %rsi, %rdi
  // 0x26ffba: je 0x26ffc2      — self-assignment: skip the copy.
  if (this_ !== other) {
    // 0x26ffbc: movq (%rsi), %rcx
    // 0x26ffbf: movq %rcx, (%rax)   ; rax == rdi == this_
    this_.type_at_0x0 = other.type_at_0x0;
    this_.flags_at_0x4 = other.flags_at_0x4;
  }
  // 0x26ffc2..0x26ffc3: pop rbp; ret  — rax still == this_.
  return this_;
}

/**
 * `OZPlaybackEngine::operator==(OZPlaybackEngine const&) const`
 * @Ozone 0x26ffd0 (__ZNK16OZPlaybackEngineeqERKS_).
 *
 * Two 32-bit field-wise compares. NOT a single 64-bit compare — the
 * compiler emitted:
 *   if (this->+0x0 != other->+0x0) return false;      // @0x26ffd4..0x26ffd8
 *   return this->+0x4 == other->+0x4;                 // @0x26ffda..0x26ffe0
 * The behaviour is IDENTICAL to a single 64-bit compare for the well-
 * defined enum+flags representation (both fields are plain integers, no
 * padding, no float NaN quirks), but we mirror the two-step compare
 * because that is what the machine does — a padding-tolerant implementer
 * writing a wider compare would silently produce different results if
 * this struct ever grew padding.
 */
export function OZPlaybackEngine_operator_eq(
  this_: OZPlaybackEngine,
  other: OZPlaybackEngine,
): boolean {
  // 0x26ffd4: movl (%rdi), %eax
  // 0x26ffd6: cmpl (%rsi), %eax
  // 0x26ffd8: jne 0x26ffe5   — return false path
  if ((this_.type_at_0x0 | 0) !== (other.type_at_0x0 | 0)) {
    // 0x26ffe5: xorl %eax, %eax; retq  -> false
    return false;
  }
  // 0x26ffda: movl 0x4(%rdi), %eax
  // 0x26ffdd: cmpl 0x4(%rsi), %eax
  // 0x26ffe0: sete %al       -> bool result
  return (this_.flags_at_0x4 | 0) === (other.flags_at_0x4 | 0);
}
